name: Tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: |
            .install
            .luarocks
          key: ${{ runner.os }}-lint-${{ hashFiles('todays-date') }}
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4
      - name: Prepare
        run: make dev_install
      - name: Lint
        run: make lint fmt_check

  unit_tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
            manager: sudo apt-get
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-linux64.tar.gz
            manager: sudo apt-get
          - os: macos-11
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
            manager: brew
          - os: macos-11
            url: https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-macos.tar.gz
            manager: brew
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-appimage-${{ hashFiles('todays-date') }}
      - name: Prepare
        run: |
          ${{ matrix.manager }} update
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
